export enum ESharedAction {
  NAVIGATE = '[Shared] Navigate',
  SUCCESS_MESSAGES = '[Shared] Success Messages',
  ERROR_MESSAGES = '[Shared] Error Messages',
  OPEN_DIALOG = '[Shared] Open Dialog',
  OPEN_DIALOG_SUCCESS = '[Shared] Open Dialog Success',
  CLOSE_DIALOG = '[Shared] Close Dialog ',
  CLOSE_DIALOG_SUCCESS = '[Shared] Close Dialog Success',
  OPEN_SPINNER = '[Shared] Open Spinner',
  CLOSE_SPINNER = '[Shared] Close Spinner',
  SET_ACTIVE_ROUTE_SUCCESS = '[Shared] Set Active Route Success',
  GET_CURRENT_MONTH = '[Shared] Get Current Month',
  GET_CURRENT_MONTH_SUCESS = '[Shared] Get Current Month Sucess',
  GET_CURRENT_MONTH_NUMBER = '[Shared] Get Current Month Number',
  GET_CURRENT_MONTH_NUMBER_SUCESS = '[Shared] Get Current Month Number Sucess',
  CHANGE_CURRENT_MONTH_NUMBER = '[Shared] Change Current Month Number',
  CHANGE_CURRENT_MONTH_NUMBER_SUCESS = '[Shared] Change Current Month Number Sucess',


  GET_SMALL_CALENDAR_CURRENT_MONTH = '[Shared] Get Small Calendar Current Month',
  GET_SMALL_CALENDAR_CURRENT_MONTH_SUCESS = '[Shared] Get Small Calendar Current Month Sucess',
  GET_SMALL_CALENDAR_CURRENT_MONTH_NUMBER = '[Shared] Get Small Calendar Current Month Number',
  GET_SMALL_CALENDAR_CURRENT_MONTH_NUMBER_SUCESS = '[Shared] Get Small Calendar Current Month Number Sucess',
  CHANGE_SMALL_CALENDAR_CURRENT_MONTH_NUMBER = '[Shared] Change Small Calendar Current Month Number',
}
